[package]
name = "ThermodynamimcComputing"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
rand = "0.9.2"
colored = "3.0.0"
ratatui = { version = "0.28.1", features = ["crossterm"] }
crossterm = "0.29.0"
